name: Nightly Tests

on:
  schedule:
    - cron: "0 5 * * 0"  # cron is UTC, this translates to 10 PM PST Sunday.
  # This lets us trigger the workflow from a browser.
  workflow_dispatch:

jobs:
  ios-nightly:
    strategy:
      fail-fast: false
      matrix:
        macos: [macos-15]
        ios: [^18]
        xcode: [^16, ^26]
        # Valid combinations that will run:
        # - iOS ^18 + Xcode ^16
        # - iOS ^18 + Xcode ^26
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
      macos: ${{ matrix.macos }}
    secrets: inherit